services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb-server
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"
    volumes:
      - ./.data/couchdb/data:/opt/couchdb/data
      - ./.data/couchdb/config:/opt/couchdb/etc/local.d
    restart: unless-stopped
